version: '3.4'

services:
  microservice_integra_dados:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice_integra_dados
    image: microservice_integra_dados
    ports:
      - "7001:7001"
    environment:
      ASPNETCORE_ENVIRONMENT: ${PHYSIS_ENV}
      #aspnet atribui o valor de MongoDb__ConnectionString definido no docker-compose para Section MongoDb__ConnectionString{MongoDb__ConnectionString:}
      MongoDb__ConnectionString: ${PHYSIS_MONGO_DB}
      #aspnet atribui o valor de Kakfa__BootstrapServers definido no docker-compose para Section Kafka{BootstrapServers:}
      Kafka__BootstrapServers: ${KAFKA_BROKER_1}
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 60G
        reservations:
          cpus: '0.40'
          memory: 40G
    
networks:
  default:
    external:
      name: bluenetwork